name: "sigstore-conformance"
author: "Alex Cameron <alex.cameron@trailofbits.com>"
description: "Conformance testing for Sigstore clients"

inputs:
  entrypoint:
    description: "the command to invoke the Sigstore client"
    required: true
    default: ""
  internal-be-careful-debug:
    description: "run with debug logs (default false)"
    required: false
    default: "false"
  skip-signing:
    description: "skip tests that involve signing (default false)"
    required: false
    default: "false"
  enable-staging:
    description: "Test against staging infrastructure as well as production (default false)"
    required: false
    default: "false"
  xfail:
    description: "one or more tests that are expected to fail, whitespace-separated"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up sigstore-conformance
      run: |
        # NOTE: Sourced, not executed as a script.
        source "${{ github.action_path }}/setup/setup.bash"
      shell: bash

    - name: Run sigstore-conformance
      id: sigstore-conformance
      run: |
        ${{ github.action_path }}/action.py
      env:
        GHA_SIGSTORE_CONFORMANCE_ENABLE_STAGING: "${{ inputs.enable-staging }}"
        GHA_SIGSTORE_CONFORMANCE_ENTRYPOINT: "${{ inputs.entrypoint }}"
        GHA_SIGSTORE_CONFORMANCE_INTERNAL_BE_CAREFUL_DEBUG: "${{ inputs.internal-be-careful-debug }}"
        GHA_SIGSTORE_CONFORMANCE_SKIP_SIGNING: "${{ inputs.skip-signing }}"
        GHA_SIGSTORE_CONFORMANCE_XFAIL: "${{ inputs.xfail }}"
        GHA_SIGSTORE_GITHUB_TOKEN: "${{ github.token }}"
      shell: bash
