name: "sigstore-conformance"
author: "Alex Cameron <alex.cameron@trailofbits.com>"
description: "Conformance testing for Sigstore clients"

inputs:
  entrypoint:
    description: "the command to invoke the Sigstore client"
    required: true
    default: ""
  internal-be-careful-debug:
    description: "run with debug logs (default false)"
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Check permissions
      if: github.event_name == 'pull_request_target' && !contains(github.event.pull_request.labels.*.name, 'safe to test')
      run: |
        echo "This pull request is not tagged with the 'safe to test' label"
        exit 1
      shell: bash

    - name: Set up sigstore-conformance
      run: |
        # NOTE: Sourced, not executed as a script.
        source "${{ github.action_path }}/setup/setup.bash"
      shell: bash

    - name: Run sigstore-conformance
      id: sigstore-conformance
      run: |
        ${{ github.action_path }}/action.py
      env:
        GHA_SIGSTORE_CONFORMANCE_ENTRYPOINT: "${{ inputs.entrypoint }}"
        GHA_SIGSTORE_CONFORMANCE_INTERNAL_BE_CAREFUL_DEBUG: "${{ inputs.internal-be-careful-debug }}"
      shell: bash
