#!/bin/sh

# This is the selftest-client for sigstore-conformance test suite
# It is a wrapper to call sigstore-python-conformance in the correct virtualenv

BASEDIR=$(dirname "$0")
VENV_PATH="${GHA_SIGSTORE_CONFORMANCE_SELFTEST_ENV:-$BASEDIR/selftest-env}"

if [ ! -f "$VENV_PATH/bin/python" ]; then
    echo "self-test virtualenv not found, please run 'make selftest-env'" >&2
    exit 1
fi

"$VENV_PATH/bin/python" "$BASEDIR/sigstore-python-conformance" "$@"