#!/usr/bin/env python3

"""
A wrapper to convert `sigstore-conformance` CLI protocol invocations to match `sigstore-python`.
"""

import os
import sys

# Trim the script name.
fixed_args = sys.argv[1:]

# Replace incompatible flags.
fixed_args = [arg if arg != "--certificate-oidc-issuer" else "--cert-oidc-issuer" for arg in fixed_args]

# Prepend the `sigstore-python` executable name.
fixed_args = ["sigstore-python"] + fixed_args

sys.exit(os.system(' '.join(fixed_args)))
